name: CI

on:
  push:
    branches:
      - main

jobs:
  create-version-build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.export.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Version
        id: export
        uses: paulhatch/semantic-version@v5.3.0
        with:
          bump_each_commit: true
  push-tag:
    runs-on: ubuntu-latest
    needs: create-version-build
    env:
      VERSION: ${{needs.create-version-build.outputs.version}}
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.VERSION }}',
              sha: context.sha
            })